### PR TITLE
Use "encoding : base64" for "Modifier" argument

### PR DESCRIPTION
**Pull request by chaosben**
As mentioned here: https://github.com/bbbco/insomnia-plugin-faker/issues/4#issuecomment-683209114

### CODE REVIEW

**Comment by bbbco** [comment]
Thanks for this! Please squash your commits, and then that should do it!

**Comment by chaosben** [comment]
I'm sorry ... im not familiar with git.
I've done something, which i thought of being "squashing" but im not sure.
Maybe it makes more sense if you change it by your own. :-)

**Comment by bbbco** [comment]
Here's a guide:
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by chaosben** [comment]
Sorry ... too complicated ... i'll do it again in a clean way. :-D

**Pull request closed without merging**
